spring:
  datasource:
    url: jdbc:mysql:///jxc
    password: 123456
    username: root
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800

  
